plugins:
  # Enable the gRPC auth service for envoy
  envoy.ext_authz.grpc:
    addr: localhost:9191
    query: data.http.api.authz.allow

# Pull policy configuration from S3
services:
  s3:
    url: https://${POLICY_BUCKET}
    credentials:
      s3_signing:
        metadata_credentials:
          aws_region: ${AWS_REGION}

# Use the policy bundle from S3 and poll for new config every 10-20 seconds, jittered
bundles:
  authz:
    service: s3
    resource: ${POLICY_BUNDLE}
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 20